# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7.xci
# IP: The module: 'base_m06_regslice_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m06_regslice_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m06_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7.xci
# IP: The module: 'base_m06_regslice_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m06_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/pynq/workspace/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_7/base_m06_regslice_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m06_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
